name: Dispatch-CI-CreateAssessment

on:
  repository_dispatch:
    type: 'TriggerContainerScanAssessment'    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ds-ms/asc-assessment@master
      name: "Create Assessment"
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ds-ms
          cluster-name: ds-ms
          code: Healthy
          severity: High
          assessment-title: 'GitHub action container scan - Dispatch trigger'
