on: [push]

env:
  REGISTRY_NAME: dsmsacr
  CLUSTER_NAME: ds-ms-k8s
  CLUSTER_RESOURCE_GROUP: ds-ms
  NAMESPACE: default
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}

    - uses: azure/container-scan@v0
      name: Container Scan 
      continue-on-error: true
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
        run-quality-checks: 'false'

    - name: Trigger Test run
      if: github.ref == 'refs/heads/master'
      run: |
       response=$(curl -X POST -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/dispatches --data '{"event_type": "TriggerContainerScanAssessment", "client_payload": {"commit": "${{ github.event.push.head_commit }}", "repository":  "${{ github.repository }}" }}')
       if [ "$response" == "" ]; then 
        echo "Triggering assessment creation succeeded"; 
       else 
        echo "Triggering integration tests failed with: '$response'";
       fi 
